version: '3.8'
services:
  postgres:
    container_name: pdpproject-postgres
    build:
      context: ./
      dockerfile: ./docker/postgres/Dockerfile
    image: pdpproject-postgres
    restart: always
    ports:
      - '${PG_PORT}:5432'
    environment:
      POSTGRES_DB: '${PG_NAME}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    container_name: pdpproject-api
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    image: pdpproject-api
    command: >
      bash -c "npm run prisma:migrate:deploy && npm run prisma:generate && npm run start:prod"
    depends_on:
      - postgres
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
volumes:
  postgres: