version: '3.8'
services:
  database:
    container_name: database
    image: 'pgrouting/osm'
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - postgres:/var/lib/postgresql/data
      # copy the script to create postgis and pgrouting extensions
      # - ./sql-scripts/1-init-extensions.sql:/docker-entrypoint-initdb.d/1-init-extensions.sql
      # 
      # - ./sql-scripts/2-seed-osm-data.sh:/docker-entrypoint-initdb.d/2-seed-osm-data.sh
      # copy script for changing weights to prioritize pedestrian and cycle ways
      # - ./sql-scripts/4-change-weights-for-pedestrian.sql:/docker-entrypoint-initdb.d/4-change-weights-for-pedestrian.sql
      # populate the table
      # - ./sql-scripts/insert-rows.sql:/docker-entrypoint-initdb.d/2-insert-rows.sql
      # configure graph topology
      # - ./sql-scripts/create-topology.sql:/docker-entrypoint-initdb.d/3-create-topology.sql
      # copy the osm data
      # - ./osm-data/switzerland-exact.osm.pbf:/usr/share/switzerland-exact.osm.pbf
      # copy the osm style configuration
      # - ./osm-data/custom.style:/usr/share/osm2pgsql/custom.style
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: root@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres:
  # pgadmin-data: